var practice_stimuli = [
  {
    "block_number": "practice",
    "triad": 1,
    "target_image_pair": "apple-horse",
    "part": "priming",
    "prime_word": "boff",
    "target_word": "apple",
    "type": "novel",
    "correct": 1,
    "image_path": "applehorse.png",
    "correct_key": "A",
    "": "practice"
  },
  {
    "block_number": "practice",
    "triad": 2,
    "target_image_pair": "apple-horse",
    "part": "priming",
    "prime_word": "mipp",
    "target_word": "horse",
    "type": "novel",
    "correct": 3,
    "image_path": "applehorse.png",
    "correct_key": "L",
    "": "practice"
  },
  {
    "block_number": "practice",
    "triad": 2,
    "target_image_pair": "apple-horse",
    "part": "priming",
    "prime_word": "geck",
    "target_word": "horse",
    "type": "novel",
    "correct": 3,
    "image_path": "applehorse.png",
    "correct_key": "L",
    "": "practice"
  },
  {
    "block_number": "practice",
    "triad": 1,
    "target_image_pair": "horse-apple",
    "part": "priming",
    "prime_word": "boff",
    "target_word": "apple",
    "type": "novel",
    "correct": 3,
    "image_path": "horseapple.png",
    "correct_key": "L",
    "": "practice"
  },
  {
    "block_number": "practice",
    "triad": 1,
    "target_image_pair": "apple-horse",
    "part": "priming",
    "prime_word": "mipp",
    "target_word": "apple",
    "type": "novel",
    "correct": 1,
    "image_path": "applehorse.png",
    "correct_key": "A",
    "": "practice"
  },
  {
    "block_number": "practice",
    "triad": 2,
    "target_image_pair": "apple-horse",
    "part": "priming",
    "prime_word": "geck",
    "target_word": "horse",
    "type": "novel",
    "correct": 3,
    "image_path": "applehorse.png",
    "correct_key": "L",
    "": "practice"
  },
  {
    "block_number": "practice",
    "triad": 2,
    "target_image_pair": "apple-horse",
    "part": "priming",
    "prime_word": "boff",
    "target_word": "horse",
    "type": "novel",
    "correct": 3,
    "image_path": "applehorse.png",
    "correct_key": "L",
    "": "practice"
  },
  {
    "block_number": "practice",
    "triad": 1,
    "target_image_pair": "horse-apple",
    "part": "priming",
    "prime_word": "mipp",
    "target_word": "apple",
    "type": "novel",
    "correct": 3,
    "image_path": "horseapple.png",
    "correct_key": "L",
    "": "practice"
  },
  {
    "block_number": "practice",
    "triad": 1,
    "target_image_pair": "apple-horse",
    "part": "priming",
    "prime_word": "geck",
    "target_word": "apple",
    "type": "novel",
    "correct": 1,
    "image_path": "applehorse.png",
    "correct_key": "A",
    "": "practice"
  },
]
var test_stimuli = [
  {
    "block_number": 1,
    "triad": 1,
    "target_image_pair": "apple-horse",
    "part": "priming",
    "prime_word": "nuppical",
    "target_word": "apple",
    "type": "familiar",
    "correct": 1,
    "image_path": "applehorse.png",
    "correct_key": "A",
    "": ""
  },
  {
    "block_number": 1,
    "triad": 1,
    "target_image_pair": "apple-horse",
    "part": "priming",
    "prime_word": "foobly",
    "target_word": "apple",
    "type": "familiar",
    "correct": 1,
    "image_path": "applehorse.png",
    "correct_key": "A",
    "": ""
  },
  {
    "block_number": 1,
    "triad": 1,
    "target_image_pair": "apple-horse",
    "part": "priming",
    "prime_word": "dodish",
    "target_word": "apple",
    "type": "familiar",
    "correct": 1,
    "image_path": "applehorse.png",
    "correct_key": "A",
    "": ""
  },
  {
    "block_number": 1,
    "triad": 1,
    "target_image_pair": "apple-horse",
    "part": "priming",
    "prime_word": "geck",
    "target_word": "apple",
    "type": "novel",
    "correct": 1,
    "image_path": "applehorse.png",
    "correct_key": "A",
    "": ""
  },
  {
    "block_number": 1,
    "triad": 1,
    "target_image_pair": "apple-horse",
    "part": "priming",
    "prime_word": "mipp",
    "target_word": "apple",
    "type": "novel",
    "correct": 1,
    "image_path": "applehorse.png",
    "correct_key": "A",
    "": ""
  },
  {
    "block_number": 1,
    "triad": 1,
    "target_image_pair": "apple-horse",
    "part": "priming",
    "prime_word": "boff",
    "target_word": "apple",
    "type": "novel",
    "correct": 1,
    "image_path": "applehorse.png",
    "correct_key": "A",
    "": ""
  },
  {
    "block_number": 1,
    "triad": 1,
    "target_image_pair": "apple-horse",
    "part": "priming",
    "prime_word": "foobly",
    "target_word": "horse",
    "type": "familiar",
    "correct": 3,
    "image_path": "applehorse.png",
    "correct_key": "L",
    "": ""
  },
  {
    "block_number": 1,
    "triad": 2,
    "target_image_pair": "apple-horse",
    "part": "priming",
    "prime_word": "nuppical",
    "target_word": "horse",
    "type": "familiar",
    "correct": 3,
    "image_path": "applehorse.png",
    "correct_key": "L",
    "": ""
  },
  {
    "block_number": 1,
    "triad": 2,
    "target_image_pair": "apple-horse",
    "part": "priming",
    "prime_word": "dodish",
    "target_word": "horse",
    "type": "familiar",
    "correct": 3,
    "image_path": "applehorse.png",
    "correct_key": "L",
    "": ""
  },
  {
    "block_number": 1,
    "triad": 2,
    "target_image_pair": "apple-horse",
    "part": "priming",
    "prime_word": "geck",
    "target_word": "horse",
    "type": "novel",
    "correct": 3,
    "image_path": "applehorse.png",
    "correct_key": "L",
    "": ""
  },
  {
    "block_number": 1,
    "triad": 2,
    "target_image_pair": "apple-horse",
    "part": "priming",
    "prime_word": "mipp",
    "target_word": "horse",
    "type": "novel",
    "correct": 3,
    "image_path": "applehorse.png",
    "correct_key": "L",
    "": ""
  },
  {
    "block_number": 1,
    "triad": 2,
    "target_image_pair": "apple-horse",
    "part": "priming",
    "prime_word": "boff",
    "target_word": "horse",
    "type": "novel",
    "correct": 3,
    "image_path": "applehorse.png",
    "correct_key": "L",
    "": ""
  },
  {
    "block_number": 1,
    "triad": 2,
    "target_image_pair": "horse-apple",
    "part": "priming",
    "prime_word": "foobly",
    "target_word": "apple",
    "type": "familiar",
    "correct": 3,
    "image_path": "horseapple.png",
    "correct_key": "L",
    "": ""
  },
  {
    "block_number": 1,
    "triad": 1,
    "target_image_pair": "horse-apple",
    "part": "priming",
    "prime_word": "nuppical",
    "target_word": "apple",
    "type": "familiar",
    "correct": 3,
    "image_path": "horseapple.png",
    "correct_key": "L",
    "": ""
  },
  {
    "block_number": 1,
    "triad": 1,
    "target_image_pair": "horse-apple",
    "part": "priming",
    "prime_word": "dodish",
    "target_word": "apple",
    "type": "familiar",
    "correct": 3,
    "image_path": "horseapple.png",
    "correct_key": "L",
    "": ""
  },
  {
    "block_number": 1,
    "triad": 1,
    "target_image_pair": "horse-apple",
    "part": "priming",
    "prime_word": "geck",
    "target_word": "apple",
    "type": "novel",
    "correct": 3,
    "image_path": "horseapple.png",
    "correct_key": "L",
    "": ""
  },
  {
    "block_number": 1,
    "triad": 1,
    "target_image_pair": "horse-apple",
    "part": "priming",
    "prime_word": "mipp",
    "target_word": "apple",
    "type": "novel",
    "correct": 3,
    "image_path": "horseapple.png",
    "correct_key": "L",
    "": ""
  },
  {
    "block_number": 1,
    "triad": 1,
    "target_image_pair": "horse-apple",
    "part": "priming",
    "prime_word": "boff",
    "target_word": "apple",
    "type": "novel",
    "correct": 3,
    "image_path": "horseapple.png",
    "correct_key": "L",
    "": ""
  },
  {
    "block_number": 1,
    "triad": 1,
    "target_image_pair": "horse-apple",
    "part": "priming",
    "prime_word": "foobly",
    "target_word": "horse",
    "type": "familiar",
    "correct": 1,
    "image_path": "horseapple.png",
    "correct_key": "A",
    "": ""
  },
  {
    "block_number": 1,
    "triad": 2,
    "target_image_pair": "horse-apple",
    "part": "priming",
    "prime_word": "nuppical",
    "target_word": "horse",
    "type": "familiar",
    "correct": 1,
    "image_path": "horseapple.png",
    "correct_key": "A",
    "": ""
  },
  {
    "block_number": 1,
    "triad": 2,
    "target_image_pair": "horse-apple",
    "part": "priming",
    "prime_word": "dodish",
    "target_word": "horse",
    "type": "familiar",
    "correct": 1,
    "image_path": "horseapple.png",
    "correct_key": "A",
    "": ""
  },
  {
    "block_number": 1,
    "triad": 2,
    "target_image_pair": "horse-apple",
    "part": "priming",
    "prime_word": "geck",
    "target_word": "horse",
    "type": "novel",
    "correct": 1,
    "image_path": "horseapple.png",
    "correct_key": "A",
    "": ""
  },
  {
    "block_number": 1,
    "triad": 2,
    "target_image_pair": "horse-apple",
    "part": "priming",
    "prime_word": "mipp",
    "target_word": "horse",
    "type": "novel",
    "correct": 1,
    "image_path": "horseapple.png",
    "correct_key": "A",
    "": ""
  },
  {
    "block_number": 1,
    "triad": 2,
    "target_image_pair": "horse-apple",
    "part": "priming",
    "prime_word": "boff",
    "target_word": "horse",
    "type": "novel",
    "correct": 1,
    "image_path": "horseapple.png",
    "correct_key": "A",
    "": ""
  },
  {
    "block_number": 1,
    "triad": 2,
    "target_image_pair": "apple-horse",
    "part": "priming",
    "prime_word": "foobly",
    "target_word": "apple",
    "type": "familiar",
    "correct": 1,
    "image_path": "applehorse.png",
    "correct_key": "A",
    "": ""
  },
  {
    "block_number": 1,
    "triad": 1,
    "target_image_pair": "apple-horse",
    "part": "priming",
    "prime_word": "nuppical",
    "target_word": "apple",
    "type": "familiar",
    "correct": 1,
    "image_path": "applehorse.png",
    "correct_key": "A",
    "": ""
  },
  {
    "block_number": 1,
    "triad": 1,
    "target_image_pair": "apple-horse",
    "part": "priming",
    "prime_word": "dodish",
    "target_word": "apple",
    "type": "familiar",
    "correct": 1,
    "image_path": "applehorse.png",
    "correct_key": "A",
    "": ""
  },
  {
    "block_number": 1,
    "triad": 1,
    "target_image_pair": "apple-horse",
    "part": "priming",
    "prime_word": "geck",
    "target_word": "apple",
    "type": "novel",
    "correct": 1,
    "image_path": "applehorse.png",
    "correct_key": "A",
    "": ""
  },
  {
    "block_number": 1,
    "triad": 1,
    "target_image_pair": "apple-horse",
    "part": "priming",
    "prime_word": "mipp",
    "target_word": "apple",
    "type": "novel",
    "correct": 1,
    "image_path": "applehorse.png",
    "correct_key": "A",
    "": ""
  },
  {
    "block_number": 1,
    "triad": 1,
    "target_image_pair": "apple-horse",
    "part": "priming",
    "prime_word": "boff",
    "target_word": "apple",
    "type": "novel",
    "correct": 1,
    "image_path": "applehorse.png",
    "correct_key": "A",
    "": ""
  },
  {
    "block_number": 1,
    "triad": 1,
    "target_image_pair": "apple-horse",
    "part": "priming",
    "prime_word": "foobly",
    "target_word": "horse",
    "type": "familiar",
    "correct": 3,
    "image_path": "applehorse.png",
    "correct_key": "L",
    "": ""
  },
  {
    "block_number": 1,
    "triad": 2,
    "target_image_pair": "apple-horse",
    "part": "priming",
    "prime_word": "nuppical",
    "target_word": "horse",
    "type": "familiar",
    "correct": 3,
    "image_path": "applehorse.png",
    "correct_key": "L",
    "": ""
  },
  {
    "block_number": 1,
    "triad": 2,
    "target_image_pair": "apple-horse",
    "part": "priming",
    "prime_word": "dodish",
    "target_word": "horse",
    "type": "familiar",
    "correct": 3,
    "image_path": "applehorse.png",
    "correct_key": "L",
    "": ""
  },
  {
    "block_number": 1,
    "triad": 2,
    "target_image_pair": "apple-horse",
    "part": "priming",
    "prime_word": "geck",
    "target_word": "horse",
    "type": "novel",
    "correct": 3,
    "image_path": "applehorse.png",
    "correct_key": "L",
    "": ""
  },
  {
    "block_number": 1,
    "triad": 2,
    "target_image_pair": "apple-horse",
    "part": "priming",
    "prime_word": "mipp",
    "target_word": "horse",
    "type": "novel",
    "correct": 3,
    "image_path": "applehorse.png",
    "correct_key": "L",
    "": ""
  },
  {
    "block_number": 1,
    "triad": 2,
    "target_image_pair": "apple-horse",
    "part": "priming",
    "prime_word": "boff",
    "target_word": "horse",
    "type": "novel",
    "correct": 3,
    "image_path": "applehorse.png",
    "correct_key": "L",
    "": ""
  },
  {
    "block_number": 1,
    "triad": 2,
    "target_image_pair": "horse-apple",
    "part": "priming",
    "prime_word": "foobly",
    "target_word": "apple",
    "type": "familiar",
    "correct": 3,
    "image_path": "horseapple.png",
    "correct_key": "L",
    "": ""
  },
  {
    "block_number": 1,
    "triad": 1,
    "target_image_pair": "horse-apple",
    "part": "priming",
    "prime_word": "nuppical",
    "target_word": "apple",
    "type": "familiar",
    "correct": 3,
    "image_path": "horseapple.png",
    "correct_key": "L",
    "": ""
  },
  {
    "block_number": 1,
    "triad": 1,
    "target_image_pair": "horse-apple",
    "part": "priming",
    "prime_word": "dodish",
    "target_word": "apple",
    "type": "familiar",
    "correct": 3,
    "image_path": "horseapple.png",
    "correct_key": "L",
    "": ""
  },
  {
    "block_number": 1,
    "triad": 1,
    "target_image_pair": "horse-apple",
    "part": "priming",
    "prime_word": "geck",
    "target_word": "apple",
    "type": "novel",
    "correct": 3,
    "image_path": "horseapple.png",
    "correct_key": "L",
    "": ""
  },
  {
    "block_number": 1,
    "triad": 1,
    "target_image_pair": "horse-apple",
    "part": "priming",
    "prime_word": "mipp",
    "target_word": "apple",
    "type": "novel",
    "correct": 3,
    "image_path": "horseapple.png",
    "correct_key": "L",
    "": ""
  },
  {
    "block_number": 1,
    "triad": 1,
    "target_image_pair": "horse-apple",
    "part": "priming",
    "prime_word": "boff",
    "target_word": "apple",
    "type": "novel",
    "correct": 3,
    "image_path": "horseapple.png",
    "correct_key": "L",
    "": ""
  },
  {
    "block_number": 1,
    "triad": 1,
    "target_image_pair": "horse-apple",
    "part": "priming",
    "prime_word": "foobly",
    "target_word": "horse",
    "type": "familiar",
    "correct": 1,
    "image_path": "horseapple.png",
    "correct_key": "A",
    "": ""
  },
  {
    "block_number": 1,
    "triad": 2,
    "target_image_pair": "horse-apple",
    "part": "priming",
    "prime_word": "nuppical",
    "target_word": "horse",
    "type": "familiar",
    "correct": 1,
    "image_path": "horseapple.png",
    "correct_key": "A",
    "": ""
  },
  {
    "block_number": 1,
    "triad": 2,
    "target_image_pair": "horse-apple",
    "part": "priming",
    "prime_word": "dodish",
    "target_word": "horse",
    "type": "familiar",
    "correct": 1,
    "image_path": "horseapple.png",
    "correct_key": "A",
    "": ""
  },
  {
    "block_number": 1,
    "triad": 2,
    "target_image_pair": "horse-apple",
    "part": "priming",
    "prime_word": "geck",
    "target_word": "horse",
    "type": "novel",
    "correct": 1,
    "image_path": "horseapple.png",
    "correct_key": "A",
    "": ""
  },
  {
    "block_number": 1,
    "triad": 2,
    "target_image_pair": "horse-apple",
    "part": "priming",
    "prime_word": "mipp",
    "target_word": "horse",
    "type": "novel",
    "correct": 1,
    "image_path": "horseapple.png",
    "correct_key": "A",
    "": ""
  },
  {
    "block_number": 1,
    "triad": 2,
    "target_image_pair": "horse-apple",
    "part": "priming",
    "prime_word": "boff",
    "target_word": "horse",
    "type": "novel",
    "correct": 1,
    "image_path": "horseapple.png",
    "correct_key": "A",
    "": ""
  },
  {
    "block_number": "",
    "triad": 2,
    "target_image_pair": "",
    "part": "",
    "prime_word": "",
    "target_word": "",
    "type": "",
    "correct": "",
    "image_path": "",
    "correct_key": "",
    "": ""
  }
]