var practice_stimuli = [
    {
      "block_number": "practice",
      "triad": 1,
      "target_image_pair": "apple-horse",
      "part": "priming",
      "prime_word": "boff",
      "target_word": "apple",
      "type": "novel",
     //get rid of relatedness and type bc we're not experimenting with co-occurrence
      "correct_response": 1,
      "image_path": "applehorse2.png",
      "correct_key": "A"
    },
    {
      "block_number": "practice",
      "triad": 2,
      "target_image_pair": "apple-horse",
      "part": "priming",
      "prime_word": "nuppical",
      "target_word": "horse",
      "type": "novel",
      "relatedness": "novel",
      "correct_response": 3,
      "image_path": "applehorse2.png",
      "correct_key": "L"
    },
    {
      "block_number": "practice",
      "triad": 2,
      "target_image_pair": "apple-horse",
      "part": "priming",
      "prime_word": "boff",
      "target_word": "horse",
      "type": "novel",
      "relatedness": "novel",
      "correct_response": 3,
      "image_path": "applehorse2.png",
      "correct_key": "L"
    },
    {
      "block_number": "practice",
      "triad": 1,
      "target_image_pair": "horse-apple",
      "part": "priming",
      "prime_word": "nuppical",
      "target_word": "apple",
      "type": "novel",
      "relatedness": "novel",
      "correct_response": 3,
      "image_path": "horseapple2.png",
      "correct_key": "L"
    },
    {
      "block_number": "practice",
      "triad": 1,
      "target_image_pair": "apple-horse",
      "part": "priming",
      "prime_word": "boff",
      "target_word": "apple",
      "type": "novel",
      "relatedness": "novel",
      "correct_response": 1,
      "image_path": "applehorse2.png",
      "correct_key": "A"
    },
    {
      "block_number": "practice",
      "triad": 2,
      "target_image_pair": "apple-horse",
      "part": "priming",
      "prime_word": "nuppical",
      "target_word": "horse",
      "type": "novel",
      "relatedness": "novel",
      "correct_response": 3,
      "image_path": "applehorse2.png",
      "correct_key": "L"
    },
    {
      "block_number": "practice",
      "triad": 2,
      "target_image_pair": "apple-horse",
      "part": "priming",
      "prime_word": "boff",
      "target_word": "horse",
      "type": "novel",
      "relatedness": "novel",
      "correct_response": 3,
      "image_path": "applehorse2.png",
      "correct_key": "L"
    },
    {
      "block_number": "practice",
      "triad": 1,
      "target_image_pair": "horse-apple",
      "part": "priming",
      "prime_word": "nuppical",
      "target_word": "apple",
      "type": "novel",
      "relatedness": "novel",
      "correct_response": 3,
      "image_path": "horseapple2.png",
      "correct_key": "L"
    },
  
  ]
  
  var test_stimuli = [
  
    {
      "block_number": 1,
      "triad": 1,
      "target_image_pair": "apple-horse",
      "part": "priming",
      "prime_word": "foobly",
      "target_word": "apple",
      "type": "direct",
      "relatedness": "related",
      "correct_response": 1,
      "image_path": "applehorse2.png",
      "correct_key": "A"
    },
    {
      "block_number": 1,
      "triad": 1,
      "target_image_pair": "apple-horse",
      "part": "priming",
      "prime_word": "mipp",
      "target_word": "apple",
      "type": "shared",
      "relatedness": "unrelated",
      "correct_response": 1,
      "image_path": "applehorse2.png",
      "correct_key": "A"
    },
    {
      "block_number": 1,
      "triad": 1,
      "target_image_pair": "apple-horse",
      "part": "priming",
      "prime_word": "dodish",
      "target_word": "apple",
      "type": "direct",
      "relatedness": "unrelated",
      "correct_response": 1,
      "image_path": "applehorse2.png",
      "correct_key": "A"
    },
  
    {
      "block_number": 1,
      "triad": 1,
      "target_image_pair": "apple-horse",
      "part": "priming",
      "prime_word": "nuppical",
      "target_word": "apple",
      "type": "novel",
      "relatedness": "novel",
      "correct_response": 1,
      "image_path": "applehorse2.png",
      "correct_key": "A"
    },
    {
      "block_number": 1,
      "triad": 1,
      "target_image_pair": "apple-horse",
      "part": "priming",
      "prime_word": "boff",
      "target_word": "apple",
      "type": "novel",
      "relatedness": "novel",
      "correct_response": 1,
      "image_path": "applehorse2.png",
      "correct_key": "A"
    },
    {
      "block_number": 1,
      "triad": 2,
      "target_image_pair": "apple-horse",
      "part": "priming",
      "prime_word": "foobly",
      "target_word": "horse",
      "type": "direct",
      "relatedness": "unrelated",
      "correct_response": 3,
      "image_path": "applehorse2.png",
      "correct_key": "L"
    },
    {
      "block_number": 1,
      "triad": 2,
      "target_image_pair": "apple-horse",
      "part": "priming",
      "prime_word": "mipp",
      "target_word": "horse",
      "type": "shared",
      "relatedness": "unrelated",
      "correct_response": 3,
      "image_path": "applehorse2.png",
      "correct_key": "L"
    },
    {
      "block_number": 1,
      "triad": 2,
      "target_image_pair": "apple-horse",
      "part": "priming",
      "prime_word": "dodish",
      "target_word": "horse",
      "type": "direct",
      "relatedness": "related",
      "correct_response": 3,
      "image_path": "applehorse2.png",
      "correct_key": "L"
    },
  
    {
      "block_number": 1,
      "triad": 2,
      "target_image_pair": "apple-horse",
      "part": "priming",
      "prime_word": "nuppical",
      "target_word": "horse",
      "type": "novel",
      "relatedness": "novel",
      "correct_response": 3,
      "image_path": "applehorse2.png",
      "correct_key": "L"
    },
    {
      "block_number": 1,
      "triad": 2,
      "target_image_pair": "apple-horse",
      "part": "priming",
      "prime_word": "boff",
      "target_word": "horse",
      "type": "novel",
      "relatedness": "novel",
      "correct_response": 3,
      "image_path": "applehorse2.png",
      "correct_key": "L"
    },
    {
      "block_number": 1,
      "triad": 1,
      "target_image_pair": "horse-apple",
      "part": "priming",
      "prime_word": "foobly",
      "target_word": "apple",
      "type": "direct",
      "relatedness": "related",
      "correct_response": 3,
      "image_path": "horseapple2.png",
      "correct_key": "L"
    },
    {
      "block_number": 1,
      "triad": 1,
      "target_image_pair": "horse-apple",
      "part": "priming",
      "prime_word": "mipp",
      "target_word": "apple",
      "type": "shared",
      "relatedness": "related",
      "correct_response": 3,
      "image_path": "horseapple2.png",
      "correct_key": "L"
    },
    {
      "block_number": 1,
      "triad": 1,
      "target_image_pair": "horse-apple",
      "part": "priming",
      "prime_word": "dodish",
      "target_word": "apple",
      "type": "direct",
      "relatedness": "unrelated",
      "correct_response": 3,
      "image_path": "horseapple2.png",
      "correct_key": "L"
    },

    {
      "block_number": 1,
      "triad": 1,
      "target_image_pair": "horse-apple",
      "part": "priming",
      "prime_word": "nuppical",
      "target_word": "apple",
      "type": "novel",
      "relatedness": "novel",
      "correct_response": 3,
      "image_path": "horseapple2.png",
      "correct_key": "L"
    },
    {
      "block_number": 1,
      "triad": 1,
      "target_image_pair": "horse-apple",
      "part": "priming",
      "prime_word": "boff",
      "target_word": "apple",
      "type": "novel",
      "relatedness": "novel",
      "correct_response": 3,
      "image_path": "horseapple2.png",
      "correct_key": "L"
    },
    {
      "block_number": 1,
      "triad": 2,
      "target_image_pair": "horse-apple",
      "part": "priming",
      "prime_word": "foobly",
      "target_word": "horse",
      "type": "direct",
      "relatedness": "unrelated",
      "correct_response": 1,
      "image_path": "horseapple2.png",
      "correct_key": "A"
    },
    {
      "block_number": 1,
      "triad": 2,
      "target_image_pair": "horse-apple",
      "part": "priming",
      "prime_word": "mipp",
      "target_word": "horse",
      "type": "shared",
      "relatedness": "unrelated",
      "correct_response": 1,
      "image_path": "horseapple2.png",
      "correct_key": "A"
    },
    {
      "block_number": 1,
      "triad": 2,
      "target_image_pair": "horse-apple",
      "part": "priming",
      "prime_word": "dodish",
      "target_word": "horse",
      "type": "direct",
      "relatedness": "related",
      "correct_response": 1,
      "image_path": "horseapple2.png",
      "correct_key": "A"
    },
    {
      "block_number": 1,
      "triad": 2,
      "target_image_pair": "horse-apple",
      "part": "priming",
      "prime_word": "nuppical",
      "target_word": "horse",
      "type": "novel",
      "relatedness": "novel",
      "correct_response": 1,
      "image_path": "horseapple2.png",
      "correct_key": "A"
    },
    {
      "block_number": 1,
      "triad": 2,
      "target_image_pair": "horse-apple",
      "part": "priming",
      "prime_word": "boff",
      "target_word": "horse",
      "type": "novel",
      "relatedness": "novel",
      "correct_response": 1,
      "image_path": "horseapple2.png",
      "correct_key": "A"
    },
    {
      "block_number": 1,
      "triad": 1,
      "target_image_pair": "apple-horse",
      "part": "priming",
      "prime_word": "foobly",
      "target_word": "apple",
      "type": "direct",
      "relatedness": "related",
      "correct_response": 1,
      "image_path": "applehorse2.png",
      "correct_key": "A"
    },
    {
      "block_number": 1,
      "triad": 1,
      "target_image_pair": "apple-horse",
      "part": "priming",
      "prime_word": "mipp",
      "target_word": "apple",
      "type": "shared",
      "relatedness": "related",
      "correct_response": 1,
      "image_path": "applehorse2.png",
      "correct_key": "A"
    },
    {
      "block_number": 1,
      "triad": 1,
      "target_image_pair": "apple-horse",
      "part": "priming",
      "prime_word": "dodish",
      "target_word": "apple",
      "type": "direct",
      "relatedness": "unrelated",
      "correct_response": 1,
      "image_path": "applehorse2.png",
      "correct_key": "A"
    },

    {
      "block_number": 1,
      "triad": 1,
      "target_image_pair": "apple-horse",
      "part": "priming",
      "prime_word": "nuppical",
      "target_word": "apple",
      "type": "novel",
      "relatedness": "novel",
      "correct_response": 1,
      "image_path": "applehorse2.png",
      "correct_key": "A"
    },
    {
      "block_number": 1,
      "triad": 1,
      "target_image_pair": "apple-horse",
      "part": "priming",
      "prime_word": "boff",
      "target_word": "apple",
      "type": "novel",
      "relatedness": "novel",
      "correct_response": 1,
      "image_path": "applehorse2.png",
      "correct_key": "A"
    },
    {
      "block_number": 1,
      "triad": 2,
      "target_image_pair": "apple-horse",
      "part": "priming",
      "prime_word": "foobly",
      "target_word": "horse",
      "type": "direct",
      "relatedness": "unrelated",
      "correct_response": 3,
      "image_path": "applehorse2.png",
      "correct_key": "L"
    },
    {
      "block_number": 1,
      "triad": 2,
      "target_image_pair": "apple-horse",
      "part": "priming",
      "prime_word": "mipp",
      "target_word": "horse",
      "type": "shared",
      "relatedness": "unrelated",
      "correct_response": 3,
      "image_path": "applehorse2.png",
      "correct_key": "L"
    },
    {
      "block_number": 1,
      "triad": 2,
      "target_image_pair": "apple-horse",
      "part": "priming",
      "prime_word": "dodish",
      "target_word": "horse",
      "type": "direct",
      "relatedness": "related",
      "correct_response": 3,
      "image_path": "applehorse2.png",
      "correct_key": "L"
    },
  
    {
      "block_number": 1,
      "triad": 2,
      "target_image_pair": "apple-horse",
      "part": "priming",
      "prime_word": "nuppical",
      "target_word": "horse",
      "type": "novel",
      "relatedness": "novel",
      "correct_response": 3,
      "image_path": "applehorse2.png",
      "correct_key": "L"
    },
    {
      "block_number": 1,
      "triad": 2,
      "target_image_pair": "apple-horse",
      "part": "priming",
      "prime_word": "boff",
      "target_word": "horse",
      "type": "novel",
      "relatedness": "novel",
      "correct_response": 3,
      "image_path": "applehorse2.png",
      "correct_key": "L"
    },
    {
      "block_number": 1,
      "triad": 1,
      "target_image_pair": "horse-apple",
      "part": "priming",
      "prime_word": "foobly",
      "target_word": "apple",
      "type": "direct",
      "relatedness": "related",
      "correct_response": 3,
      "image_path": "horseapple2.png",
      "correct_key": "L"
    },
    {
      "block_number": 1,
      "triad": 1,
      "target_image_pair": "horse-apple",
      "part": "priming",
      "prime_word": "mipp",
      "target_word": "apple",
      "type": "shared",
      "relatedness": "related",
      "correct_response": 3,
      "image_path": "horseapple2.png",
      "correct_key": "L"
    },
    {
      "block_number": 1,
      "triad": 1,
      "target_image_pair": "horse-apple",
      "part": "priming",
      "prime_word": "dodish",
      "target_word": "apple",
      "type": "direct",
      "relatedness": "unrelated",
      "correct_response": 3,
      "image_path": "horseapple2.png",
      "correct_key": "L"
    },
 
    {
      "block_number": 1,
      "triad": 1,
      "target_image_pair": "horse-apple",
      "part": "priming",
      "prime_word": "nuppical",
      "target_word": "apple",
      "type": "novel",
      "relatedness": "novel",
      "correct_response": 3,
      "image_path": "horseapple2.png",
      "correct_key": "L"
    },
    {
      "block_number": 1,
      "triad": 1,
      "target_image_pair": "horse-apple",
      "part": "priming",
      "prime_word": "boff",
      "target_word": "apple",
      "type": "novel",
      "relatedness": "novel",
      "correct_response": 3,
      "image_path": "horseapple2.png",
      "correct_key": "L"
    },
    {
      "block_number": 1,
      "triad": 2,
      "target_image_pair": "horse-apple",
      "part": "priming",
      "prime_word": "foobly",
      "target_word": "horse",
      "type": "direct",
      "relatedness": "unrelated",
      "correct_response": 1,
      "image_path": "horseapple2.png",
      "correct_key": "A"
    },
    {
      "block_number": 1,
      "triad": 2,
      "target_image_pair": "horse-apple",
      "part": "priming",
      "prime_word": "mipp",
      "target_word": "horse",
      "type": "shared",
      "relatedness": "unrelated",
      "correct_response": 1,
      "image_path": "horseapple2.png",
      "correct_key": "A"
    },
    {
      "block_number": 1,
      "triad": 2,
      "target_image_pair": "horse-apple",
      "part": "priming",
      "prime_word": "dodish",
      "target_word": "horse",
      "type": "direct",
      "relatedness": "related",
      "correct_response": 1,
      "image_path": "horseapple2.png",
      "correct_key": "A"
    },

    {
      "block_number": 1,
      "triad": 2,
      "target_image_pair": "horse-apple",
      "part": "priming",
      "prime_word": "nuppical",
      "target_word": "horse",
      "type": "novel",
      "relatedness": "novel",
      "correct_response": 1,
      "image_path": "horseapple2.png",
      "correct_key": "A"
    },
    {
      "block_number": 1,
      "triad": 2,
      "target_image_pair": "horse-apple",
      "part": "priming",
      "prime_word": "boff",
      "target_word": "horse",
      "type": "novel",
      "relatedness": "novel",
      "correct_response": 1,
      "image_path": "horseapple2.png",
      "correct_key": "A"
    }
  ]